wget wwtweb.blob.core.windows.net/docs/images/Polys.bmp
wget wwtweb.blob.core.windows.net/docs/images/NYAndromeda.jpg
wget wwtweb.blob.core.windows.net/docs/images/NYAndromedaNoHorizon.jpg
wget wwtweb.blob.core.windows.net/docs/images/LocalSydney.jpg
wget wwtweb.blob.core.windows.net/docs/images/EarthNoClouds.jpg
wget wwtweb.blob.core.windows.net/docs/images/EarthClouds.jpg
wget wwtweb.blob.core.windows.net/docs/images/Boundarys.jpg
wget wwtweb.blob.core.windows.net/docs/images/Figures.jpg
wget wwtweb.blob.core.windows.net/docs/images/Selection.jpg
wget wwtweb.blob.core.windows.net/docs/images/CrossHairs.jpg
wget wwtweb.blob.core.windows.net/docs/images/Ecliptic.jpg
wget wwtweb.blob.core.windows.net/docs/images/ElevationFlat.jpg
wget wwtweb.blob.core.windows.net/docs/images/ElevationModel.jpg
wget wwtweb.blob.core.windows.net/docs/images/FOV.jpg
wget wwtweb.blob.core.windows.net/docs/images/EGrid.jpg
wget wwtweb.blob.core.windows.net/docs/images/SaturnLighting.jpg
wget wwtweb.blob.core.windows.net/docs/images/SaturnMilkyWay.jpg
wget wwtweb.blob.core.windows.net/docs/images/CarribeanLowRes.jpg
wget wwtweb.blob.core.windows.net/docs/images/CarribeanHiRes.jpg
wget wwtweb.blob.core.windows.net/docs/images/SaturnOrbits.jpg
wget wwtweb.blob.core.windows.net/docs/images/SunActual.jpg
wget wwtweb.blob.core.windows.net/docs/images/SunFull.jpg
wget wwtweb.blob.core.windows.net/docs/images/SaturnStars.jpg
wget wwtweb.blob.core.windows.net/docs/images/Circles.jpg
wget wwtweb.blob.core.windows.net/docs/images/Polygons.jpg
wget wwtweb.blob.core.windows.net/docs/images/Polylines.jpg
wget wwtweb.blob.core.windows.net/docs/images/endtourdialog.jpg
wget wwtweb.blob.core.windows.net/docs/images/BackgroundImage.jpg
